routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\ProductRatings\Http\Controllers\ProductRatingController;
use Bittacora\Bpanel4\ProductRatings\Http\Controllers\ProductRatingsAdminController;
use Illuminate\Support\Facades\Route;

Route::prefix('/opiniones-de-productos')->name('bpanel4-product-ratings.')->middleware(['web'])
    ->group(static function (): void {
        Route::post('/store', [ProductRatingController::class, 'store'])->name('store');
    });

Route::prefix('bpanel/opiniones-de-productos')->name('bpanel4-product-ratings.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function (): void {
        Route::get('/listar', [ProductRatingsAdminController::class, 'index'])->name('index');
        Route::get('/{rating}/editar', [ProductRatingsAdminController::class, 'edit'])->name('edit');
        Route::post('/actualizar', [ProductRatingsAdminController::class, 'update'])->name('update');
        Route::delete('/eliminar', [ProductRatingsAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/_form.blade.php
<?php /** @var \Bittacora\Bpanel4\ProductRatings\Models\ProductRating|null $rating */ ?>
<form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
    @csrf
    <div class="form-group form-row">
        <div class="col-sm-3 col-form-label text-sm-right">
            <label class="mb-0  ">
                {{ __('bpanel4-product-ratings::general.client') }}
            </label>
        </div>
        <div class="col-sm-7 d-flex align-items-center">
            <div class="input-group m-b">
                <a href="{{ route('bpanel4-clients.edit', ['client' => $rating->client_id]) }}" target="_blank">{{ $rating->getClient()->getFullName() }} <i class="fas fa-external-link-alt"></i></a>
            </div>
        </div>
    </div>
    <div class="form-group form-row">
        <div class="col-sm-3 col-form-label text-sm-right">
            <label class="mb-0  ">
                {{ __('bpanel4-product-ratings::general.product') }}
            </label>
        </div>
        <div class="col-sm-7 d-flex align-items-center">
            <div class="input-group m-b">
                <a href="{{ route('bpanel4-products.edit', ['model' => $rating->product_id]) }}" target="_blank">{{ $rating->getProduct()->getName() }} <i class="fas fa-external-link-alt"></i></a>
            </div>
        </div>
    </div>
    <div class="form-group form-row">
        <div class="col-sm-3 col-form-label text-sm-right">
            <label class="mb-0  ">
                {{ __('bpanel4-product-ratings::general.rating') }}
            </label>
        </div>
        <div class="col-sm-7 d-flex align-items-center">
            <div class="input-group m-b">
                @include('bpanel4-product-ratings::partials.star-rating', ['value' => $rating['rating']])
            </div>
        </div>
    </div>
    @livewire('form::input-text', ['name' => 'title', 'labelText' => __('bpanel4-product-ratings::general.title'),
    'required'=>true, 'value' => old('title') ?? $rating?->getTitle() ])
    @livewire('form::textarea', ['name' => 'message', 'labelText' =>
    __('bpanel4-product-ratings::general.message'), 'value' => old('message') ??
    $rating?->getMessage() ])
    @livewire('form::input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => old('active') ?? $rating?->isActive(), 'labelText' => __('bpanel4-product-ratings::general.active'), 'bpanelForm' => true])
    <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
    @if($rating?->getId() !== null)
        <input type="hidden" name="id" value="{{ $rating->getId() }}">
    @endif

    @if(isset($language))
        <input type="hidden" name="locale" value="{{ $language }}">
    @endif
    <style>
        .star-rating .stars {
            display: flex;
            gap: 0.5rem;
            align-items: flex-end;
            line-height: 1em;
            color: #ffb433;
        }
    </style>
</form>

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Editar opinión')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-product-ratings::general.edit') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @include('bpanel4-product-ratings::bpanel._form')
        </div>
    </div>


@endsection

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Opiniones de productos')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-product-ratings::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-product-ratings::livewire.ratings-table', [], key('bpanel4-product-ratings-datatable'))
        </div>
    </div>


@endsection

resources/views/bpanel/livewire/product-datatable.blade.php
<?php /** @var \Bittacora\Bpanel4\ProductRatings\Models\ProductRating $row */ ?>
<td>
    <a href="{{ route('bpanel4-clients.edit', ['client' => $row->client_id]) }}" target="_blank">{{ $row->getClient()->getFullName() }} <i class="fas fa-external-link-alt"></i></a>
</td>
<td>
    <a href="{{ route('bpanel4-products.edit', ['model' => $row->product_id]) }}" target="_blank">{{ $row->getProduct()->getName() }} <i class="fas fa-external-link-alt"></i></a>
</td>
<td class="text-center">
    @if($row->rating >= 4)
        <span class="badge badge-pill badge-success">{{ $row->rating }}</span>
    @elseif($row->rating >= 3)
        <span class="badge badge-pill badge-warning">{{ $row->rating }}</span>
    @else
        <span class="badge badge-pill badge-danger">{{ $row->rating }}</span>
    @endif
</td>
<td>
    {{ substr($row->message, 0, 60) }} @if(strlen($row->message) > 60)...@endif
</td>
<td>
    {{ substr($row->message, 0, 60) }} @if(strlen($row->message) > 60)...@endif
</td>
<td class="align-middle">
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-product-ratings', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'la valoración?'], key('rating-buttons-'.$row->id))
    </div>
</td>

resources/views/livewire/_form.blade.php
<!--suppress HtmlFormInputWithoutLabel -->
@auth
    <form class="product-rating-form" method="post" action="{{ route('bpanel4-product-ratings.store') }}">
        @csrf
        <div class="form-group mb-4 title">
            <input type="text" class="form-control" id="title" placeholder="Título de su opinión" name="title">
        </div>
        <div class="form-group mb-4 message">
            <textarea class="form-control" placeholder="Escriba aquí su opinión sobre el producto." name="text"></textarea>
        </div>
        <div class="form-group d-flex align-items-center rating-row mb-4">
            <div class="pr-3">Valoración del producto</div>
            @include('bpanel4-product-ratings::partials.star-rating', ['value' => 5, 'fieldId' => 'rating'])
        </div>
        <input type="hidden" name="product_id" value="{{ Crypt::encryptString($product->getId()) }}">
        <button type="submit" class="btn btn-primary">Enviar</button>
        @if($errors->any())
            {!! implode('', $errors->all('<div>:message</div>')) !!}
        @endif
    </form>
@elseguest
    <div class="alert alert-warning product-ratings-warning">
        <i class="fas fa-exclamation-triangle"></i> {{ __('bpanel4-product-ratings::public.must-be-logged-in') }}
    </div>
@endauth

resources/views/livewire/list.blade.php
<div>
    @include('bpanel4-product-ratings::livewire._form', ['product' => $product])
    <div class="ratings">
        @forelse($ratings as $rating)
            <div class="rating">
                <div class="title">
                    <div>{{ $rating['title'] }}</div>
                    <div class="date">{{ date_format(new DateTime($rating['created_at']), 'd\/m\/y') }}</div>
                </div>
                <div class="client-name">
                    {{ $rating['client']['name'] }} {{ $rating['client']['surname'] }}
                    <div class="client-stars">
                        @include('bpanel4-product-ratings::partials.star-rating', ['value' => $rating['rating']])
                    </div>
                </div>
                <div class="message">
                    {{ $rating['message'] }}
                </div>
            </div>
        @empty
            <p class="no-ratings-yet">{{ __('bpanel4-product-ratings::public.no-ratings-yet') }}</p>
        @endforelse
        <div class="ratings-pagination">
            {{ $ratings->links() }}
        </div>
    </div>
</div>

resources/views/partials/star-rating.blade.php
<div class="star-rating" @if(isset($fieldId)) id="{{ $fieldId }}" data-enabled="true" @else data-enabled="false"
     @endif data-selected-value="{{ $value }}"  data-current-value="">
    <div class="stars" >
        @for($i=0; $i<5; $i++)
            <div class="star">
                @if($value - $i >= 1)
                    <i class="fas fa-star"></i>
                @elseif($value - $i >= .5)
                    <i class="fad fa-star-half"></i>
                @else
                    <i class="far fa-star"></i>
                @endif
            </div>
        @endfor
    </div>
    @if(isset($fieldId))
        <input type="hidden" name="{{ $fieldId }}" value="" class="rating-input">
    @endif
</div>